version: '3'

services:
  mysql:
    image: mysql
    network_mode: host
    container_name: mysqlcont
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_UST_SAMPLE: jdbc:mysql://localhost:3306/dockdb?createDatabaseIfNotExist=true&user=root&password=password

  myorder:
    image: maryrani/orderimg
    network_mode: host
    restart: always
    depends_on:
      - mysql
    ports:
      - 9092:9092
    healthcheck:
      test: 'exit 0'
    